server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/info_aggregation?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  config-locations: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
